version: '3'
services:
  llonebot-docker:
    image: garrise/ll-cc-docker:vnc
    tty: true
    container_name: llonebot-docker
    restart: always
    ports:
      - "5900:5900"
      - "3000:3000"    
      - "3001:3001"
    # - "3001:3001" 留给反向
    environment:
      - TZ=Asia/Shanghai
      - VNC_PASSWD=vncpasswd
    volumes:
      - ./LiteLoader/:/opt/QQ/resources/app/LiteLoader
      # 未固化QQ数据 当前仅固化LiteLoader
